### ISSUE TITLE
Can't add P1 meter "Could not connect to meter"

### ISSUE THREAD

**Issue by Argon007** [ryhazerus/EnergyDashboardWebDisplay#1]
Hi,

I like the Homewizard Energy Dashboard and i'm happy to see that someone cloned the interface. I just installed the application in Docker and can connect to it via http://192.168.1.201:8001 .

My HomeWizard P1 meter has a static IP address (by DHCP reservation 192.168.1.102). When I try to add the meter I get the message "Could not connect to meter". The Local API is enabled since the meter is also in Home Assistant (and is working perfectly).
When I browse to http://192.168.1.102 I get the following "Nothing matches the given URI".

Any clue what can be wrong or what I can try?

Thanks!

**Comment by ryhazerus** [comment]
@Argon007  Sorry about the super late reply. I haven't been pushing updates to Github lately. Did you ever get the issue fixed or would still like some help?

**Comment by ryhazerus** [comment]
Seems this was caused by the optional user_gas_prices field not actually being optional. I created a fix and merged it. You can pull the latest changes and perform `docker compose up --build -d` to rebuild the dockerfiles and see the new implementation. You might also have to do a hard refresh in your browser to get the latest changes. But its unlikely.
